name: Run-In-Docker

env:
  PYTHON_VERSION: '3.11'              # set this to the Python version to use
  PROJECT_NAME: my_project
  PROJECT_DIR: my_app
  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: master

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Verify folder
        run:
          ls -al

      - name: Build and run
        run:
          docker build .
