name: My-Github-Action

env:
  PYTHON_VERSION: '3.11'              # set this to the Python version to use
  PROJECT_NAME: my_project
  PROJECT_DIR: my_dir
  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv
            !.git/
            !.gitignore/
            !.github/

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
          
      - name: Verif
        run:
          ls -al
          
      - name: Prepare Workdir 
        shell: bash
        run: |
          mkdir ${{env.my_dir}}
          mv * ${{env.my_dir}}
          
      - name: start virtual environment
        working-directory: ${{env.my_dir}}
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Start application
        working-directory: ${{env.my_dir}}
        run:
          ls -al
          python3 main.py
